
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Sep 19 21:40:23 CEST 2012
//----------------------------------------------------

package compiler.synanal;

/** CUP generated class containing symbol constants. */
public class PascalTok {
  /* terminals */
  public static final int CHAR_CONST = 3;
  public static final int VAL = 37;
  public static final int LTH = 27;
  public static final int FUNCTION = 46;
  public static final int LBRACKET = 15;
  public static final int CONST = 41;
  public static final int CHAR = 8;
  public static final int SEMIC = 19;
  public static final int PRIVATE = 10;
  public static final int INT = 9;
  public static final int ARRAY = 38;
  public static final int FOR = 45;
  public static final int NOT = 31;
  public static final int AND = 21;
  public static final int RECORD = 51;
  public static final int TYPE = 54;
  public static final int NIL = 5;
  public static final int OR = 32;
  public static final int BOOL = 7;
  public static final int COMMA = 12;
  public static final int BEGIN = 40;
  public static final int DIV = 22;
  public static final int GEQ = 24;
  public static final int IF = 47;
  public static final int ASSIGN = 39;
  public static final int UADD = 35;
  public static final int DOT = 13;
  public static final int PTR = 33;
  public static final int OF = 48;
  public static final int DOTS = 14;
  public static final int EOF = 0;
  public static final int RBRACKET = 17;
  public static final int INT_CONST = 4;
  public static final int PROGRAM = 50;
  public static final int error = 1;
  public static final int MUL = 29;
  public static final int ADD = 20;
  public static final int LPARENTHESIS = 16;
  public static final int NEQ = 30;
  public static final int GTH = 25;
  public static final int EQU = 23;
  public static final int COLON = 11;
  public static final int ELSE = 43;
  public static final int TO = 53;
  public static final int MEM = 28;
  public static final int WHILE = 56;
  public static final int THEN = 52;
  public static final int RPARENTHESIS = 18;
  public static final int LEQ = 26;
  public static final int END = 44;
  public static final int USUB = 36;
  public static final int BOOL_CONST = 2;
  public static final int SUB = 34;
  public static final int VAR = 55;
  public static final int PROCEDURE = 49;
  public static final int DO = 42;
  public static final int IDENTIFIER = 6;

  /* non terminals */
  static final int value_params = 22;
  static final int statement = 13;
  static final int value_list = 21;
  static final int constant = 18;
  static final int if_statement = 14;
  static final int type = 23;
  static final int while_statement = 15;
  static final int list_statement2 = 29;
  static final int record_type = 26;
  static final int constant_declarations = 5;
  static final int types = 9;
  static final int for_statement = 16;
  static final int assign_statement = 17;
  static final int subprogram_declarations = 8;
  static final int multiple_statement = 27;
  static final int vars = 11;
  static final int type_declaration = 19;
  static final int source = 0;
  static final int value = 20;
  static final int table_type = 25;
  static final int subprogram_head = 12;
  static final int list_statement = 28;
  static final int ptr_type = 24;
  static final int program_indication = 1;
  static final int variable_declarations = 7;
  static final int param_descr_list_r = 3;
  static final int comp_descr_list = 2;
  static final int param_descr_list = 4;
  static final int type_declarations = 6;
  static final int constants = 10;
}

